DROP TABLE IF EXISTS sparcs_discharges;

CREATE TABLE sparcs_discharges (
  health_service_area TEXT,
  hospital_county TEXT,
  operating_certificate_number TEXT,
  facility_id TEXT,
  facility_name TEXT,
  age_group TEXT,
  zip_code_3_digits TEXT,
  gender TEXT,
  race TEXT,
  ethnicity TEXT,
  length_of_stay TEXT,
  type_of_admission TEXT,
  patient_disposition TEXT,
  discharge_year INT,
  ccs_diagnosis_code TEXT,
  ccs_diagnosis_description TEXT,
  ccs_procedure_code TEXT,
  ccs_procedure_description TEXT,
  apr_drg_code TEXT,
  apr_drg_description TEXT,
  apr_mdc_code TEXT,
  apr_mdc_description TEXT,
  apr_severity_of_illness_code TEXT,
  apr_severity_of_illness_description TEXT,
  apr_risk_of_mortality TEXT,
  apr_medical_surgical_description TEXT,
  payment_typology_1 TEXT,
  payment_typology_2 TEXT,
  payment_typology_3 TEXT,
  birth_weight TEXT,
  abortion_edit_indicator TEXT,
  emergency_department_indicator TEXT,
  total_charges NUMERIC,
  total_costs NUMERIC
);